<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Vishal-Tiwari" name="ehospital.Covid_Module.TestScripts.Covid19_Admission" tests="4" failures="0" timestamp="2020-08-05T17:43:58 IST" time="58.243" errors="1">
  <testcase name="SearchUHID" time="45.279" classname="ehospital.Covid_Module.TestScripts.Covid19_Admission"/>
  <system-out>
SearchUHIDscript execution starts atWed Aug 05 17:42:59 IST 2020 SearchUHIDscript   is passed  </system-out>
  <testcase name="CovidAdmissionInAvailableGreenBed" time="2.742" classname="ehospital.Covid_Module.TestScripts.Covid19_Admission">
    <error type="org.openqa.selenium.UnhandledAlertException" message="Dismissed user prompt dialog: The patient is already admitted with CR No. 202086: 
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;VISHAL-TIWARI&#039;, ip: &#039;192.168.146.1&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_121&#039;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 78.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20200708170202, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 5612, moz:profile: C:\Users\Acer\AppData\Local..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 24a0d935-5b2b-4b5e-babf-d703c8e36f63
*** Element info: {Using=xpath, value=//input[contains(@id,&#039;address_patient_add_other&#039;)]}">
      <![CDATA[org.openqa.selenium.UnhandledAlertException: Dismissed user prompt dialog: The patient is already admitted with CR No. 202086: 
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'VISHAL-TIWARI', ip: '192.168.146.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 78.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20200708170202, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 5612, moz:profile: C:\Users\Acer\AppData\Local..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 24a0d935-5b2b-4b5e-babf-d703c8e36f63
*** Element info: {Using=xpath, value=//input[contains(@id,'address_patient_add_other')]}
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at com.sun.proxy.$Proxy9.sendKeys(Unknown Source)
at ehospital.Covid_Module.Features.Covid19Admissionhelper.selectAvialableGreenBed(Covid19Admissionhelper.java:51)
at ehospital.Covid_Module.TestScripts.Covid19_Admission.CovidAdmissionInAvailableGreenBed(Covid19_Admission.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- CovidAdmissionInAvailableGreenBed -->
  <system-out>
CovidAdmissionInAvailableGreenBedscript execution starts atWed Aug 05 17:43:44 IST 2020 CovidAdmissionInAvailableGreenBedscript  is failed Screenshot has been taken  </system-out>
  <testcase name="CovidAdmissionInBookedBed" time="5.568" classname="ehospital.Covid_Module.TestScripts.Covid19_Admission"/>
  <system-out>
CovidAdmissionInBookedBedscript execution starts atWed Aug 05 17:43:47 IST 2020 CovidAdmissionInBookedBedscript   is passed  </system-out>
  <testcase name="CovidAdmissionInComorBed" time="4.654" classname="ehospital.Covid_Module.TestScripts.Covid19_Admission"/>
  <system-out>
CovidAdmissionInComorBedscript execution starts atWed Aug 05 17:43:53 IST 2020 CovidAdmissionInComorBedscript   is passed  </system-out>
</testsuite> <!-- ehospital.Covid_Module.TestScripts.Covid19_Admission -->
